### ISSUE TITLE
FirewallCluster - VPN - Automatic Certificate Management

### ISSUE THREAD

**Issue by EtienneMILON** [Forcepoint/fp-NGFW-SMC-python#1]
Hello,

When I use the function FirewallCluster.create in smc.core.engines, the option "Automated RSA Certificate Management" in the menu "VPN > Certificate" is not enabled.
I don't find this option in the function or in the engine properties.
Is there a way to enable it when creating the engine or after?

Best regards,
Etienne

![image](https://user-images.githubusercontent.com/41421040/82445918-f5107800-9aa5-11ea-9ae5-fddc6bc7d56a.png)

**Comment by EtienneMILON** [comment]
Hi David,

On my side the first part of the code you have sent works.
But if I make then an "engine.update()", the option is disable.
And even if I try to update it with "engine.update(is_cert_auto_renewal=True)" it doesn't enable the option.

This is the code I execute:
`engine = FirewallCluster.create(
    name="mycluster_test",
    cluster_virtual="1.1.1.1",
    network_value="1.1.1.0/24",
    interface_id=0,
    macaddress="02:02:02:02:02:02",
    nodes=[
        {"address": "1.1.1.2", "network_value": "1.1.1.0/24", "nodeid": 1},
        {"address": "1.1.1.3", "network_value": "1.1.1.0/24", "nodeid": 2},
    ],
    domain_server_address=["1.1.1.1"],
    is_cert_auto_renewal=True,
)
print(engine.is_cert_auto_renewal)

engine.update()
print(engine.is_cert_auto_renewal)`

The first print output is False but in the SMC the option is ticked.
The second print output is True but in the SMC the option is unticked.
I use fp-NGFW-SMC-python 0.7.0b23.

Etienne

**Comment by thomasdevulder** [comment]
Hello Etienne,

Currently is_cert_auto_renewal attribute is not fully supported.
But it is possible to use it in the create method using extra_opts parameter:

    Layer3Firewall.create(name=engine_name,
                          mgmt_ip="192.168.10.1",
                          mgmt_network="192.168.10.0/24",
                          ntp_settings=ntp,
                          extra_opts={"is_cert_auto_renewal": True}
                          )

    engine = Layer3Firewall(engine_name)
    print("is_cert_auto_renewal={}".format(engine.is_cert_auto_renewal))
    print("update to false...")
    engine.update(is_cert_auto_renewal=False)
    print("is_cert_auto_renewal={}".format(Layer3Firewall(engine_name).is_cert_auto_renewal))

This attribute will be supported soon.

Regards,
Thomas

**Comment by lilianValeroFp** [comment]
It will be available in the next release (1.0.21), hoping beginning of the next year.

**Comment by lilianValeroFp** [comment]
Finally, there was a confusion in attributes there. You are pointing from your screenshot an InternalGateway setting 'auto_certificate' but the attribute, you are referring to 'is_cert_auto_renewal', is the engine advanced settings 'Automated Node Certificate Renewal'. So you should be able to update both from the current api.
