### ISSUE TITLE
Cannot iterate ips_ipv4_access_rules of smc.base.model.SubIpv4IpsPolicyDynamic

### ISSUE THREAD

**Issue by xschlef** [Forcepoint/fp-NGFW-SMC-python#14]
Hi,

I am using smc-python 0.6.2 with SMC 6.8 with python 3.8.

I am trying to iterate through our rulesets and I am stuck with subpolicies, as I cannot retrieve the rules contained in there.
```
# iterate through rules
...
# does not work
if action == "jump":
    for r in rule.action.sub_policy.ips_ipv4_access_rules.all():
```

all other ways of fetching the subpolicy rules manually failed.

Am I doing something wrong or is this a bug in smc-python?

Thanks

**Comment by EtienneMILON** [comment]
Hello,

I don't use SMC 6.8 but in my opinion there is two things that may be "wrong" in your code:
- Action is in "rule.action.action"
- SubPolicy cannot have IPS rules, only FW rules (so rule.action.sub_policy.fw_ipv4_access_rules)

Does it help?

Etienne

**Comment by xschlef** [comment]
Sorry that you had to wait so long:

> Action is in "rule.action.action"
action is a local variable in this case, that contains rule.action.action

> SubPolicy cannot have IPS rules, only FW rules (so rule.action.sub_policy.fw_ipv4_access_rules)

<class 'smc.base.model.SubIpv4IpsPolicyDynamic'> object has no attribute 'fw_ipv4_access_rules'>
```
print(type(rule.action.sub_policy))
<class 'smc.base.model.SubIpv4IpsPolicyDynamic'>
print(vars(rule.action.sub_policy.data))

{
    "_etag": '"OTY0MTM3MTE2MjE1MDYxNzA4NDU="',
    "data": {
        "key": 96,
        "link": [
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96",
                "rel": "self",
                "type": "sub_ipv4_ips_policy",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/export",
                "rel": "export",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/history",
                "rel": "history",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/search_category_tags_from_element",
                "rel": "search_category_tags_from_element",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/duplicate",
                "rel": "duplicate",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/force_unlock",
                "rel": "force_unlock",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/search_rule",
                "rel": "search_rule",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/duplicate_as_l2_interface",
                "rel": "duplicate_as_l2_interface",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/open",
                "rel": "open",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/save",
                "rel": "save",
            },
            {
                "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/ips_ipv4_access_rule",
                "rel": "ips_ipv4_access_rules",
                "type": "ips_ipv4_access_rule",
            },
        ],
        "name": "Land/Region",
        "read_only": False,
        "system": False,
        "system_key": -1,
    },
}
```

if I interpret the data correctly, there should be a list of access rules at ```rule.action.sub_policy.ips_ipv4_access_rules```
or am I missing something important?

**Comment by thomasdevulder** [comment]
> Sorry that you had to wait so long:
> 
> > Action is in "rule.action.action"
> > action is a local variable in this case, that contains rule.action.action
> 
> > SubPolicy cannot have IPS rules, only FW rules (so rule.action.sub_policy.fw_ipv4_access_rules)
> 
> <class 'smc.base.model.SubIpv4IpsPolicyDynamic'> object has no attribute 'fw_ipv4_access_rules'>
> 
> ```
> print(type(rule.action.sub_policy))
> <class 'smc.base.model.SubIpv4IpsPolicyDynamic'>
> print(vars(rule.action.sub_policy.data))
> 
> {
>     "_etag": '"OTY0MTM3MTE2MjE1MDYxNzA4NDU="',
>     "data": {
>         "key": 96,
>         "link": [
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96",
>                 "rel": "self",
>                 "type": "sub_ipv4_ips_policy",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/export",
>                 "rel": "export",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/history",
>                 "rel": "history",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/search_category_tags_from_element",
>                 "rel": "search_category_tags_from_element",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/duplicate",
>                 "rel": "duplicate",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/force_unlock",
>                 "rel": "force_unlock",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/search_rule",
>                 "rel": "search_rule",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/duplicate_as_l2_interface",
>                 "rel": "duplicate_as_l2_interface",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/open",
>                 "rel": "open",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/save",
>                 "rel": "save",
>             },
>             {
>                 "href": "https://...:8082/6.5/elements/sub_ipv4_ips_policy/96/ips_ipv4_access_rule",
>                 "rel": "ips_ipv4_access_rules",
>                 "type": "ips_ipv4_access_rule",
>             },
>         ],
>         "name": "Land/Region",
>         "read_only": False,
>         "system": False,
>         "system_key": -1,
>     },
> }
> ```
> 
> if I interpret the data correctly, there should be a list of access rules at `rule.action.sub_policy.ips_ipv4_access_rules`
> or am I missing something important?

You are right, rule.action.sub_policy.ips_ipv4_access_rules should return a list of rules..
It seems due to SubIpv4IpsPolicyDynamic element is dynamically created and doesn't support  ips_ipv4_access_rule..

I created an issue in Forcepoint Github Enterprise.

Thomas.

**Comment by thomasdevulder** [comment]
Issue is fixed and will be published in next release

you will be able to retrieve IPS  sub rules using: (@see examples/sub_policies.py)
```
        # retrieve rules for ips sub policy
        jump_rule = ips_policy.search_rule("ips_jump_rule")
        if jump_rule[0].action.action[0] == "jump":
            for r in jump_rule[0].action.sub_policy.ips_ipv4_access_rules.all():
                print("sub ips rule:{}".format(r))

```

**Comment by xschlef** [comment]
Thanks. I will close the issue once I am able to check.
