### ISSUE TITLE
Integration with SMC Version 6.8 // Issue with updating group members

### ISSUE THREAD

**Issue by Alrexxar** [Forcepoint/fp-NGFW-SMC-python#18]
Hi everyone,
Is there already an estimation to when SMC 6.8 will be supported? Or is this even planned?

Currently im having some issues with a script as there seem to be some changes regarding the group api entrypoints. Atleast the methods which I used in 6.7 dont work anymore.

Best Regards
Alrexxar

**Comment by ggrimaux** [comment]
Hello,

Can you give more details about what it is not working please?
Thanks in advance.

BR,
/Greg.

**Comment by Alrexxar** [comment]
Hi Greg,
Sure i can

Currently the problem exists while calling the methods described in the Group API Reference.
The easiest example would be:

`GROUPOBJECT.empty_members()`

The following exception arises:
`Traceback (most recent call last):
  File "createdcgroup.py", line 36, in <module>
    DCsGoldbeckbiz.empty_members()
  File "/usr/local/lib/python3.6/site-packages/smc/elements/group.py", line 100, in empty_members
    self.update(element=[])
  File "/usr/local/lib/python3.6/site-packages/smc/base/model.py", line 456, in update
    if self.data.get('system', False):
  File "/usr/local/lib/python3.6/site-packages/smc/base/decorators.py", line 77, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/site-packages/smc/base/model.py", line 368, in data
    return LoadElement(self.href)
  File "/usr/local/lib/python3.6/site-packages/smc/base/model.py", line 281, in __get__
    filter_context=instance.typeof)
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 151, in fetch_meta_by_name
    'exact_match': exact_match}).read()
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 75, in read
    return self._make_request(method='GET')
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 101, in _make_request
    raise err
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 86, in _make_request
    self.href = session.entry_points.get('elements')
  File "/usr/local/lib/python3.6/site-packages/smc/api/session.py", line 302, in entry_points
    raise SMCConnectionError('No entry points found, it is likely '
smc.api.exceptions.SMCConnectionError: No entry points found, it is likely there is no valid login session.
`

If you need any more information feel free to ask.
Thanks for your help

Alrexxar

**Comment by thomasdevulder** [comment]
Hello Alrexxar,

I could use correctly group functionalities using SMC 6.9 and tested with ServiceGroup element.
Used empty_members() method and it is also working for me.

Could you try following test script:

"""
Example script to show how to use group
"""

# Python Base Import
import sys
# Python SMC Import
from smc import session
from smc.elements.group import ServiceGroup
from smc.elements.service import UDPService

if __name__ == '__main__':
    URLSMC='http://localhost:8082'
    APIKEYSMC='HuphG4Uwg4dN6TyvorTR0001'
    try:
        session.login(url=URLSMC, api_key=APIKEYSMC, verify=False, timeout=120)
    except BaseException as exception_retournee:
        sys.exit(-1)

    print("session OK")
try:
    udp_service1 = UDPService.create("test udpservice1", 500)
    udp_service2 = UDPService.create("test udpservice2", 600)
    service_group = ServiceGroup.create("test service group", [udp_service1, udp_service2])
    service_group = ServiceGroup("test service group")
    elements = service_group.obtain_members()
    print("members="+str(elements))
    print("call empty members")
    service_group.**empty_members()**
    elements = service_group.obtain_members()
    print("members="+str(elements))
finally:
    service_group.delete()
    udp_service1.delete()
    udp_service2.delete()
  

for me results are:
session OK
members=[UDPService(name=test udpservice1), UDPService(name=test udpservice2)]
call empty members
members=[]

Process finished with exit code 0
