### ISSUE TITLE
Forcepoint SMC test VM?

### ISSUE THREAD

**Issue by shibumi** [Forcepoint/fp-NGFW-SMC-python#2]
Hi,
I would like to develop some open source tools based on SMC Python for Forcepoint, but I can't find any Forcepoint SMC I can test against. Do you plan to ship such a test VM via vagrant maybe?  If not, how can I test my code to make sure it's actually working on Forcepoint SMCs without spending thousands of dollars on a Forcepoint SMC?

**Comment by ggrimaux** [comment]
Hello,

Sorry but we are not planning righ to provide that kind of test env. Your company should deploy kind of PreProduction Env to test your scripts. 

BR,
/Greg

**Comment by shibumi** [comment]
Thanks!
