### ISSUE TITLE
Calling .save() on rule object changes the action to "allow"

### ISSUE THREAD

**Issue by sklamt** [Forcepoint/fp-NGFW-SMC-python#21]
Hello,

After updating to a more recent version of this library, we encountered an unexpected change in our automatically generated "jump" rules. The action of these rules was changed to "allow" after calling .save() .

This behavior seems to have been introduced in commit 45faf15a7784885e8c24bf4755f4143f974b820f . This commit changed the default of the .update() method to action="allow" . Since the .save() method calls .update() without any arguments, calling .save() on a rule with any other action than "allow" leads to an unexpected change.
 
As a workaround, I changed our Scripts to directly call the .update() method with the correct action, but this seems to be an unintended consequence of the change in the .update() behavior and should probably be addressed in the library.

Best regards,
Sebastian

**Comment by thomasdevulder** [comment]
Yes, exact, I see the problem..
I am going to open an issue in our github enterprise. and let you know when it will be fixed.

Thanks for your comment.

**Comment by thomasdevulder** [comment]
This issue has been fixed and will be included in version 1.0.14
