### ISSUE TITLE
Go SDK?

### ISSUE THREAD

**Issue by shibumi** [Forcepoint/fp-NGFW-SMC-python#22]
Hi,

is there any Go SDK for the SMC API? This repository is about the Python version and I hope that there might be a Go SDK, too.

**Comment by LilianValero** [comment]
Hi, it is an interesting request but unfortunately we didn't plan to implement / provide an SMC API lib in GO.
But if you have some questions on the API itself to manage this, we will be happy to answer them.
Have a good day.
