### ISSUE TITLE
Routing and find all networks related to some host

### ISSUE THREAD

**Issue by son432** [Forcepoint/fp-NGFW-SMC-python#25]
Hi,
I have two open issues from the previous session and I thought it would be better to gather them neatly here:
1) given a specific host get all the subnets in the smc that contain it, like the 'referenced_by' attribute but currently this attribute doesn't contain networks .
for example, I have this naive code:
def find_all_networks_contain_host(host_IP):
    all_relevant_subnets = []
    for subnet in list(Network.objects.all()):
        if 'ipv4_network' in subnet.data:
            host_address = ipaddress.ip_address(host_IP)
            curr_network = ipaddress.ip_network(str(subnet.data['ipv4_network']))
            if host_address in curr_network:
                all_relevant_subnets.append(subnet)
    print(all_relevant_subnets)

if there was a way to directly get all the networks that contains a particular host without going through all the networks that exist in the smc it would be very useful for a lot of applications.

2) given a specific host find behind which cluster it is routed in the firewall, something like "query route" in the GUI. 
currently I have only some naive code that takes a lot of time to run.

I'm working on some project of real-time rules search in the firewall and currently these two issues prevent me from running it in a reasonable amount of time. I would love to have your help:)

Thanks

**Comment by ggrimaux** [comment]
Hello,

We did created an internal improvement to support query route in SMC API. 

For your first request I'm not sure, I need to check internally. Since it is holidays times I just want to warn you that delay for answer can be longer.

Question about your first point:
Did you tried to run your code in parallel? 

Example:

Algo
* Get list of all network in SMC
* Run in parallel method using thread pool
** Have one method that checks in host is in netowrk then happened the table

Example from our code:

The following method is run in parallel (max_worker = 20, this is a good number for query SMC in API).
The goal is to run the method check_engine_status_after_policy_upload in parallel. The second param must be a list.
```
    with concurrent.futures.ThreadPoolExecutor(
            max_workers=max_workers) as executor:
        executor.map(check_engine_status_after_policy_upload,
                     engine_list)
```

In your case it could be:

```
login()

# Get all networks list
list_all_networks = list(Network.objects.all())

# Run check in parallel
with concurrent.futures.ThreadPoolExecutor(
        max_workers=20) as executor:
    executor.map(is_host_in_network,
                 list_all_networks)
                 
logout()
```

I hope this can help you to make you script faster.

**Comment by son432** [comment]
thanks,
"We did created an internal improvement to support query route in SMC API" - could you please clarify which command it is?
in addition, I have tried to add multi processing to my code before and it still didn't work so fast. 
but I will try it again with your example, any way I think it would be very helpful if there will be a way to directly get all the networks that contains a particular host using the API.

**Comment by son432** [comment]
Hi,
Is there any answer regarding to my previous question about the command that performs query route? 
I also tried to run the search of the host in all the networks in parallel like you suggested but it's still too slow because the SMC I'm working with has 20K networks. 
I will appreciate if you could add a method that directly get all the networks that contains a particular host without going through all the networks that exist in the SMC.

**Comment by ggrimaux** [comment]
Hello,

So two enhancements have been opened internally. There are not yet planned so we'll let you know once they are available.

BR,
/Greg

**Comment by son432** [comment]
hi Greg,
is there any update regarding to the two enhancements? 
in addition, you write here in the past "We did created an internal improvement to support query route in SMC API" - could you explain a little bit more about this improvement? wat are the relevant methods names in the API? 

thanks,
Son

**Comment by ggrimaux** [comment]
Hi,

It is still in progress. Once they will be available you will be noticed with more details.

BR,
/Greg

**Comment by lilianValeroFp** [comment]
query_route is not implemented yet. You could see in next releases, my guess, the 1.0.21.
