### ISSUE TITLE
Updating ipv4Rules

### ISSUE THREAD

**Issue by HoussemBouteldja** [Forcepoint/fp-NGFW-SMC-python#29]
Hello,

I try to update an ipv4Rules object with .update() methode. It doesn't work when rule name contains "/"
I get following error message.
I use fp-ngfw-smc-python~=1.0.12 and SMC 6.8.8.

`Rule @317776.13": "Invalid JSON format: For input string: \"68719491123\" (from: FWIPv4AccessRuleDTO[\"parent_insert_point\"]).`

**Comment by HoussemBouteldja** [comment]
Here is a screen shot of the rule :
![image](https://user-images.githubusercontent.com/49160244/153620090-113a44d7-66a3-4004-a04d-d0e4d39c8a77.png)

**Comment by thomasdevulder** [comment]
Hello Houssem,

The name of the rule is the part before '/', the part after is the rule tag

![image](https://user-images.githubusercontent.com/71770006/154278443-21cd1748-f2ce-4299-a90e-51227b06182e.png)

in this example: "Block by geolocation"

I tried to update the rule and it works for me using:

```
    p = FirewallPolicy("HQ Policy")

    for rule in p.fw_ipv4_access_rules.all():
        print("Rule:{} Src:{} Dst:{} Tag:{}".format(rule.name, rule.sources, rule.destinations, rule.tag))
        if rule.name == "Block by geolocation":
            print("Discard from North Korea..")
            rule.update(action="discard")

```

```
Rule:Block by geolocation Src:ANY=False, NONE=False, SOURCES=[Country(name=North Korea)] Dst:ANY=False, NONE=False, DESTINATIONS=[Zone(name=Internal)] Tag:2097332.1
Discard from North Korea..

```
I get:
![image](https://user-images.githubusercontent.com/71770006/154279762-b607be4a-293a-4aa8-a04a-7b0a2315d589.png)

Hope that could help..

Let me know,

Thomas
