### ISSUE TITLE
Changing Log Definitions 

### ISSUE THREAD

**Issue by amit3141** [Forcepoint/fp-NGFW-SMC-python#30]
Hi everyone!

I'm using python 3.8; API version 6.8; Git Hub version 3.1.27
We were adding rules with the API:

# -------------------------- creating the rule --------------------------
            options = LogOptions()
            options.log_accounting_info_mode = True
            options.log_level = 'stored'
            p.fw_ipv4_access_rules.create(name='', comment=comment, services=[service], sources=[specific_src_host], destinations=[specific_dest_host], action='allow', log_options=options)
            data.append([policy_name, section, src_ip, dest_ip, dest_port, app, app_protocol, comment, 'created the rule'])
        p.fw_ipv4_access_rules.create_rule_section(section_name)  # creating a specific section in the policy
#----------------------------------------------------------------------------

How can I change the settings of the rule-logs, such that a log wouldn't be created for connection closing:
![image](https://user-images.githubusercontent.com/100075269/154846234-4e5b12f6-e0ed-4b5c-bff0-2ae69972e0ed.png)

(want the Connection Closing value to be set to "No Log").

**Comment by ggrimaux** [comment]
Hello @amit3141,

I guess what you need to use is:

`    def log_closing_mode(self):
        """
        Specifying False means no log entries are created when
        connections are closed. True will mean both connection
        opening and closing are logged, but no information is
        collected on the volume of traffic.

        :param bool value: enable/disable accounting data
        :return: bool
        """
        return self.get("log_closing_mode")

    @log_closing_mode.setter
    def log_closing_mode(self, value):
        self.update(log_closing_mode=value)
`

Here is one quick example with lines you added in your question:
`
        options = LogOptions()
        options.log_accounting_info_mode = True
        options.log_level = 'stored'
        option.log_closing_mode = False    # No log for connection closing
        p.fw_ipv4_access_rules.create(name='', comment=comment, services=[service], sources=[specific_src_host], destinations=[specific_dest_host], action='allow', log_options=options)
        data.append([policy_name, section, src_ip, dest_ip, dest_port, app, app_protocol, comment, 'created the rule'])
    p.fw_ipv4_access_rules.create_rule_section(section_name)  # creating a specific section in the policy
`

I hope this will help you.

BR,
/Greg.
