### ISSUE TITLE
How to communicate HTTPS to SMC API using SMC-Python?

### ISSUE THREAD

**Issue by MinaGithuub** [Forcepoint/fp-NGFW-SMC-python#31]
If we configured API on SMC to use HTTPS protocol, How to communicate HTTPS to SMC API using fp-NGFW-SMC-Python and do everything with SMC via HTTPS?

**Comment by ggrimaux** [comment]
Hello,

You can find some help in the documentation:

- https://fp-ngfw-smc-python.readthedocs.io/en/latest/pages/session.html?highlight=login#configuring-credentials

```
from smc import session
session.login(url='https://1.1.1.1:8082', api_key='xxxxxxxxxxxxxxxx',
              verify='/Users/username/home/mycacert.pem')
```

Best Regards,
/Greg.
