### ISSUE TITLE
How to collect logs of specific access rule on SMC?

### ISSUE THREAD

**Issue by MinaGithuub** [Forcepoint/fp-NGFW-SMC-python#33]
I want to collect logs of specific access rule on SMC then analyze these logs and propose the recommended access rules to be created as per these logs.

How to do that?

Also how to use python machine learning for achieving this goal?

**Comment by lilianValeroFp** [comment]
I'm sorry but it appears to be a quite complex request that cannot be answered easily here. Logs can be retrieved from websocket and after that would require some human actions to be sure to not push security issue on your security device.
