### ISSUE TITLE
Unable to install other dependancy because of pytz fixed version

### ISSUE THREAD

**Issue by HoussemBouteldja** [Forcepoint/fp-NGFW-SMC-python#34]
Hello,

I'm not able to install other depandancies (ex: celery) on my project because pytz version is fixed to 2021.1 in /setup.py 
since python 3.10, other libreries requires pytz>=2021.3

Is there any reason to fix pytz version to 2021.1 ?
![image](https://user-images.githubusercontent.com/49160244/186356408-eec13f65-f946-4189-a602-c9b7c7db89bb.png)

**Comment by thomasdevulder** [comment]
Hello Houssem,

We are going update to the latest version.
It will be released in 1.0.18
thanks for your point

**Comment by HoussemBouteldja** [comment]
Thank you for the quick answere. 
When the 1.0.18 is be expected ?

**Comment by thomasdevulder** [comment]
Hello,
Version 1.0.18 just has been released.

**Comment by HoussemBouteldja** [comment]
Thank you
