### ISSUE TITLE
VPN Gateway expiration date 

### ISSUE THREAD

**Issue by sophalsun69** [Forcepoint/fp-NGFW-SMC-python#37]
Hello 

I am trying to get the expiration date, and for that I am using the smc.core.engine.VPN
and gateway_certificate . 
But the list do not return it  ! 

print(list(engineC0xxxx.vpn.gateway_certificate))
>>[GatewayCertificate(name=<O=Forcepoint, CN=LISC0xxxxSDW00 - Primary> RSA / SHA-256), GatewayCertificate(name=<O=Forcepoint, CN=LISC0xxxxSDW00 - Primary> RSA / SHA-256)]

Could you give me some tips ?

Best regards 
![tempsnipVPN_Gateway](https://user-images.githubusercontent.com/118282396/202673806-39dc79de-a206-4fa7-9a70-800840baeca0.png)

**Comment by lilianValeroFp** [comment]
Hi, we are going to add the support of that in the next release 1.0.21. Sorry for the trouble.

**Comment by sophalsun69** [comment]
Ok , thanks for the fast answer .
But could we have an idea about this release 1.0.21 ?

best regards

**Comment by lilianValeroFp** [comment]
I hope beginning of the next year.
