### ISSUE TITLE
Create users with password in InternalDomain

### ISSUE THREAD

**Issue by m0canu1** [Forcepoint/fp-NGFW-SMC-python#39]
I cannot find anywhere the possibility to create a new user in the InternalDomain with the parameter "password".

The only parameters accepted by the create function in the **create()** function of the _smc.administration.user_auth.users_ **InternalUserDomain** are: name, user_group, activation_date, expiration_date and comment.

Is there a way to add the password? Maybe adding this possibility if only using the secure channel communication (websocket)?

**Comment by lilianValeroFp** [comment]
Hi, we will add in 1.0.21 (beginning of the next year) the support of import_ldif_elements api service which will allow you to import LDIF file and so be able to import ldap internal users.

**Comment by m0canu1** [comment]
Hi @lilianValeroFp i'm trying to export_ldif_elements but I get the following error:

`smc.api.exceptions.TaskRunFailed: Resource requested: 'export_ldif_elements' is not available on this element.`

**Comment by gregory83** [comment]
Hello,

If I'm correct it is only available with SMC 7.1. and higher versions.

/Greg.

**Comment by lilianValeroFp** [comment]
Hi @m0canu1,

Yes, you need to have also the SMC version which could support it. Since, it was something which has been also implemented in SMC. We could try to put it also in 7.0.2 or in 6.10.11 if you want to?
Let us know which version of SMC could do the trick for you.

**Comment by m0canu1** [comment]
Hi @lilianValeroFp,

I am using the SMC version 6.10.7 at the moment. And should be this version for a while.

**Comment by lilianValeroFp** [comment]
Unfortunately, I'm sorry, but as I stated, the SMC 6.10.X does not have the export/import LDIF feature on the SMC API. The only thing, we may do, could be to back port the 7.1.0 improvement in 6.10.X where X >= 11. 
Since 6.10.X is a LTS SMC version and 7.1.X will be also a LTS version, do you know which SMC version might suit you?

**Comment by m0canu1** [comment]
Sorry for the misunderstanding.

I would say that 6.10.11 is ok.

**Comment by lilianValeroFp** [comment]
Ok let's try to put that in our road map.

**Comment by lilianValeroFp** [comment]
In //, we will try also to see if we can do something directly on current "internal_user" and "internal_user_group" SMC API elements on smc-python lib.

**Comment by m0canu1** [comment]
BTW, in the download center i only see the SMC 6.10.10, released yesterday.

**Comment by lilianValeroFp** [comment]
Yes that's why I told you 6.10.X where X >= 11 :)
