### ISSUE TITLE
add an IP configuration on a tunnel interface without IP

### ISSUE THREAD

**Issue by pazix** [Forcepoint/fp-NGFW-SMC-python#42]
Hello, I have a small problem to add an IP address to an existing tunnel interface.

I am having trouble adding an IP address to an existing tunnel interface on a clusterengine. Specifically, I am trying to add a /32 IP address to a tunnel interface that does not have a 'CVI Only' subinterface. I've tried several methods described in the documentation, but I keep running into JSON format errors. I have been working on this problem for two days now and could use some help.

 

here is my code
 
```
for interface in cluster.tunnel_interface.all():
    if interface.name == "Tunnel Interface 1000":
    	print(interface.addresses)
    	payload = {
    				"interfaces': [{'cluster_virtual": "77.77.77.77",
                    'network_value': "77.77.77.77/32"}]      				
                    
                       }
    	
    	interface.update(**payload)
```

`.api.exceptions.UpdateElementFailed: Invalid JSON format: Could not resolve type id 'cluster_virtual' as a subtype of `com.stonesoft.api.v14.elements.dto.storable.engine.EngineInterfaceDTO`: known type ids = [capture_interface, cluster_virtual_interface, inline_interface, inline_ips_interface, inline_l2fw_interface, node_interface, single_node_interface] (for POJO property 'interfaces') at [line: 1, column: 262] (from: ArrayList[0]).`

but when I want to change the address of an existing tunnel, I can do it 

```
for interface in cluster.tunnel_interface.all():
     if interface.name == "Tunnel Interface 1002":
    	for intf in interface.sub_interfaces():
    		if intf.address == "192.168.1.2":
    		      new_payload = {"comment": "tunnel1002",
    							"address":"192.168.1.1",
    							"network_value":"192.168.1.1/32"
        				
                    
                       }
    		intf.update(**new_payload)
    	interface.update()
```
    	
    	I thank you for your help and hope to get back to you for my problem

**Comment by amol-suruse** [comment]
Hello,

A new method 'add_ip_address' has been introduced in the Interface class (smc/core/interfaces.py) to add an IP address.

Could you please check the example file smc/examples/layer3_cluster.py in the latest fp-NGFW-SMC-python?
