### ISSUE TITLE
ServerBackupTask fails

### ISSUE THREAD

**Issue by bsecurefr** [Forcepoint/fp-NGFW-SMC-python#43]
Hi,

Trying to call 
ServerBackupTask.create(name='Backup' , servers=[ManagementServer(name='XXXXXXX')]) raise the error below : Invalid JSON format: At line 1 and column 420, **server_target_path** is not recognized as JSON attribute. <class 'smc.api.exceptions.CreateElementFailed'>
Several attemps on the parameters did not help (adding the path mainly).
Thank you

**Comment by lilianValeroFp** [comment]
Hi, it seems that smc-python has introduced a regression to support SMC < 7.0.0. So either you edit scheduled_tasks.py to comment following lines:
"server_target_path": path,
"script_to_execute": script
which are new attributes for SMC >= 7.0.0 or upgrade your SMC to >= 7.0.0. For your information, SMC 7.0.2 will be released quite soon.
We will fix the smc-python regression in the next smc-python release.
Sorry for the trouble.
