### ISSUE TITLE
Viewing an Alias' references does not show the element referenced in the Alias, only the address.

### ISSUE THREAD

**Issue by adi105** [Forcepoint/fp-NGFW-SMC-python#44]
When dereferencing an Alias object using a firewall engine name, the information returned is a list of addresses which are part of the firewall engine's Alias translation, but there is seemingly no tie in to obtain information regarding what specific elements are being referenced in the Alias. For instance, I am currently working on a deduplication/cleanup script which consolidates multiple elements into one element by moving their references to the master element, then deleting the old elements. Let us use this example scenario.

The following objects exist:
A host element with name "Host1" and address "1.2.3.4"
A host element with name "Host2" and address "1.2.3.4"
An Alias object with name "Alias1"
A firewall engine with name "Engine1"
Engine1's alias translation for Alias1 contains Host2

Let us say we are trying to move all references of Host2 to Host1 in order to delete Host2 and get rid of this duplicated element. Host2 is referenced in Engine1's address translation for Alias1. If we dereference the alias using the following code, all we can identify is that Engine1's translation for Alias1 contains IP address "1.2.3.4".
```python
alias = Alias('Alias1')
alias.resolve('Engine1')
# this would return ['1.2.3.4']
```

Within the GUI, I can identify which specific element is being referenced in that alias object. I cannot see a way to identify if Host1 or Host2 are being referenced in the Alias via smc-python. My goal is to be able to remove Host2 from this alias and add Host1 to this alias. Is there a better method known to overcome this roadblock, or is this a limitation on the capabilities of the API?

**Comment by lilianValeroFp** [comment]
Hi, the resolve Alias method will return resolved elements (if applicable) if you are using SMC >= 7.0.0. For your information, SMC 7.0.2 will be released quite soon.
