### ISSUE TITLE
Setting standby mode on a TunnelInterface

### ISSUE THREAD

**Issue by bsecurefr** [Forcepoint/fp-NGFW-SMC-python#45]
Hi,
I am trying to set the TunnelInterface in 'standy' by calling` int.update( ... , balancing_mode='standby')` but i get the error below.
`Invalid JSON format: At line 1 and column 839, balancing_mode is not recognized as JSON attribute. <class 'smc.api.exceptions.UpdateElementFailed'>`
I mentionned that `enabled=True` is working.
Thank you

**Comment by lilianValeroFp** [comment]
Hi,

"balancing_mode" is not an attribute of TunnelInterface. What do you want to do?

BR

**Comment by lilianValeroFp** [comment]
For now, it is not supported by the smc-python lib. We will try to support it in next versions.

**Comment by bsecurefr** [comment]
Thank you :)

**Comment by lilianValeroFp** [comment]
Hi,

You can try this kind of code:
  standby_con_type = ConnectionType("Standby")
  for endpoint in engine.vpn.internal_endpoint:
        endpoint.update(connection_type_ref=standby_con_type.href)
Let us know.
