### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'href'

### ISSUE THREAD

**Issue by Ethost** [Forcepoint/fp-NGFW-SMC-python#48]
Imported library :
```python
from icecream import ic
from smc import session
from smc.core.engines import FirewallCluster
from smc.elements.network import Host, Network
from smc.elements.servers import LogServer
import json
```

Python version:
![image](https://github.com/Forcepoint/fp-NGFW-SMC-python/assets/50379056/49bfc74a-72da-4295-a201-28869fe840c9)

fp-NGFW-SMC-python version :
![image](https://github.com/Forcepoint/fp-NGFW-SMC-python/assets/50379056/19c4502a-a90f-48d4-998e-cc2f3d7abb13)

_____

Hello,

I have an error when I try to create a cluster : 
![image](https://github.com/Forcepoint/fp-NGFW-SMC-python/assets/50379056/66251298-af7a-4acd-be55-8ef902599950)

I think the "LogServer.objects.first()" object does not contain the ".href" :
![image](https://github.com/Forcepoint/fp-NGFW-SMC-python/assets/50379056/a1efea9c-5a0c-49d6-a70f-1e8429e3a958)

Do you know if it is still maintained?

**Comment by Ethost** [comment]
Hello @gregory83,

I found it, it's a mistake on my part.
I restricted the token API too much, with a SuperUser API I don't get any error.

Apologize for the case, have a nice day. : )

**Comment by gregory83** [comment]
Hey no problem.

Have a nice day too.

/Greg
