### ISSUE TITLE
role 'Manage Administrator' mandatory for read only API clients

### ISSUE THREAD

**Issue by entomologe** [Forcepoint/fp-NGFW-SMC-python#50]
Hello,

I try to restrict my API client, but a plain login already needs 'Manage Administrator' from 'Administrative Rights' in 'All'. As soon I try to login I get: 
```
ERROR:root:Failed to get username, please make sure you can have 'Manage Administrator' in your role
ERROR:smc.api.session:Logout status was unexpected. Received response with status code: 401
...
```

The description for 'Manage Administrator' is: **"Allows the administrator to view and manage Administrator, Web Portal User, Administrator Role, API Clients and Access Control List elements"**.

BR, sam

**Comment by lilianValeroFp** [comment]
Hi,

The fix will be available in SMC >= 6.10.14/7.0.3/7.2.0

BR
