### ISSUE TITLE
Search a firewall policy similarly to "Search Rules" function in SMC GUI

### ISSUE THREAD

**Issue by adi105** [Forcepoint/fp-NGFW-SMC-python#54]
Hello,

I am having trouble finding a way to conclusively search a firewall policy's ruleset for all rules matching a given network element IP. Within the SMC GUI, when you preview a Firewall Policy, you can search that policy via clicking the gear cog icon in the top right corner and selecting "Search Rules". This allows you to input a IP address or Subnet within one of the fields, and the SMC will show you all matching rules in which that source IP or subnet is contained in that particular slot. This search is recursive in that it will also show you rules in which a group is used, if that group contains your target subnet or IP.

For example, let's say I have a network element "net_A" with address 1.2.3.0/24 which is referenced in 5 rules within a policy. Let us say net_A is also included in a group "group_A" and group_A is used within 15 rules in a policy. When searching with the firewall API, I am able to pull all rules from a policy and iterate through them, comparing the values in the source and destination fields via element name, or resolving each element and comparing by value. However, this will not include the references where group_A is used, so I would only find 5 rules instead of 20 matching rules.

I have tried replicating the recursion manually, but for large groups this takes a long time, especially taking into account nested groups of multiple levels. When the SMC GUI performs this search, this slowness is not observed. Using the above scenario, if I were to search using the SMC GUI search function, it would show me 20 rules.

For additional context, my end goal is to be able to determine, given a source IP/subnet, destination IP/subnet, and protocol-port, whether or not a firewall flow is allowed in a particular policy. If there is a better way to accomplish this other than searching the ruleset and matching the fields as I've described above, please let me know.

Is there a way to replicate this behavior with fp-ngfw-smc-python? In other words, using the above scenario, is there a way to obtain all 20 rules?

Thanks in advance.

**Comment by lilianValeroFp** [comment]
Hi, currently the rule query tool is available on the policy editor and it has not been planned to be put on SMC API / smc-python. It is a dedicated feature implemented on the UI and that will deserve a dedicated feature for SMC API. If you really want to implement it by yourself with SMC API/smc-python, you will need to consider the resolution of all ip values for all your impacted (referenced in your rules) network elements. Please remember that you need to consider sub rules also :) and possibly inherited rules from templates. Once you have this mapping, you will be able to construct for each rule a structure with src/dst/port (the same mechanism is applicable for tcp/udp ports) then when you want to search a tuple(src_ip, dst_ip, port) you need to go through all this structure and check with contains on each rule the src_ip/dst_ip/port. I hope that will help you on your scenario. BR
