### ISSUE TITLE
engine.routing_monitoring Error 

### ISSUE THREAD

**Issue by FeedMeY** [Forcepoint/fp-NGFW-SMC-python#57]
Hey, Im trying to fetching data from a domain in smc.

in specific engines (FW's) that im trying to get te routing monitoring - the program failed and i got an exepction :

**smc.api.exceptions.EngineCommandFailed: Impossible to retrieve session monitoring entry for Id[************].**

this is the part of the code that's making the fetch :

                            for route in engine.routing_monitoring:
                                if(route.route_type != 'Connected') and (route.route_netmask != 32):
                                    netMaskGen = route.route_network + '/' + str(route.route_netmask)
                                    connection_entry = {
                                    "Source_NetMask": netMaskGen,
                                    "Route_gateway": route.route_gateway
                                }
                                firewall_entry["Connections"].append(connection_entry)  
                            print('Finish Fetch : ' + engine.name)
                            print('#############################################################\n')
                            
suddenly when I'm trying to do fetch a lot of time, the FW that timeout the program is fetching the data and other FW crashig.

(its important to sat that in other domains its work good).

in want to know if there is a try exception that can chack if the fetch fail - > and if yes it will try again untill it wil succeded.

And if there is other option to resolve the problem it will great!

Thank.

**Comment by amol-suruse** [comment]
Hi,
This exception occurs when the engine is offline. Could you please check if the engine is online and try again?

**Comment by FeedMeY** [comment]
hey, in the logic of the code i check if the engine is online, and only if its online its doing the fetch, example from the code:
            if word_to_find not in cluster.name and word_to_find1 not in cluster.name and **engine.nodes[0].health.engine_node_status == 'Online'**:
            
so the issue is not because the engine is offline, also i am checking the engine in the smc portal and his online.

maybe we can chat and try to resolve it together?

everything in the engine is OK so it possible a issue with fetching the data.

**Comment by FeedMeY** [comment]
> Hi, This exception occurs when the engine is offline. Could you please check if the engine is online and try again?

hey, in the logic of the code i check if the engine is online, and only if its online its doing the fetch, example from the code:
if word_to_find not in cluster.name and word_to_find1 not in cluster.name and engine.nodes[0].health.engine_node_status == 'Online':

so the issue is not because the engine is offline, also i am checking the engine in the smc portal and his online.

maybe we can chat and try to resolve it together?

everything in the engine is OK so it possible a issue with fetching the data.

**Comment by amol-suruse** [comment]
Hello 
The issue is not related to smc-python; smc-python does not get responses from the management server side; we need to investigate it from the engine and management server sides.
So you should take standard support by opening a ticket on support.

**Comment by FeedMeY** [comment]
> Hello The issue is not related to smc-python; smc-python does not get responses from the management server side; we need to investigate it from the engine and management server sides. So you should take standard support by opening a ticket on support.

hello, thank you for helping me, do you have a link to open a ticket on suport? thanks.

**Comment by lilianValeroFp** [comment]
Hi @FeedMeY,  you should be able to login to Customer Hub in https://support.forcepoint.com/s/
Technical Contacts and Superusers have Cases option at top of window.
