### ISSUE TITLE
Session Login via alt_filepath / config file: configparser removed in Python 3.12

### ISSUE THREAD

**Issue by lsteingass** [Forcepoint/fp-NGFW-SMC-python#59]
Hey, Im trying to create a session using a config file specified via the 'alt_filepath' option.
Since python-3.12 the configparser module, which is used to parse the config file, was [removed](https://docs.python.org/3/whatsnew/3.11.html#standard-library) and subsequently the session creation fails with the following error:
``` 
Traceback (most recent call last):
  File "/root/test.py", line 13, in <module>
    session.login(alt_filepath='/root/test.config')
  File "/usr/local/lib/python3.12/dist-packages/fp_NGFW_SMC_python-1.0.25-py3.12.egg/smc/api/session.py", line 544, in login
    load_from_file(alt_filepath) if alt_filepath is not None else load_from_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/fp_NGFW_SMC_python-1.0.25-py3.12.egg/smc/api/configloader.py", line 157, in load_from_file
    parser = configparser.SafeConfigParser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
Are there any plans on bringing this feature back/ fixing it for new python versions?

Thank you!

**Comment by amol-suruse** [comment]
Hello
Yes, we have created a ticket to fix this issue. We will fix this issue in the next release.

**Comment by lsteingass** [comment]
Thank you very much! 

I will close this issue now.

Best Regards
Lennart
