### ISSUE TITLE
Get Network or Host from IP/CIDR

### ISSUE THREAD

**Issue by matthieuy** [Forcepoint/fp-NGFW-SMC-python#61]
Hello,

How to get a host object from his IP and not his object name ?
The method Host::get() accept only name.

I suppose I need to use a slightly more global method (SMCRequest?). A loop is not possible given the number of objects, so I hope a filter exists.

Sorry if the question seems silly but I couldn't find anything in the examples.

**Comment by gregory83** [comment]
Hello,

Have you tried something like this?
* https://fp-ngfw-smc-python.readthedocs.io/en/latest/pages/collections.html#basic-rules-on-searching

```
list(Router.objects.filter(address='10.10.10.1'))
-- [Router(name=Router-10.10.10.1)]
```

BR,

/Greg.
