### ISSUE TITLE
Exporting elements from a FIPs enabled device

### ISSUE THREAD

**Issue by oleksandriegorov** [Forcepoint/fp-NGFW-SMC-python#65]
How to supply a password in python's API to "export_elements" granted that SMC is FIPS enabled?
Tried to use it as is and getting the error: "Error occurred during export file: You must provide a password to encrypt export file."

Here is Export all elements in FIPS KB article for UI:
https://help.forcepoint.com/ngfw/en-us/6.11.0/GUID-14764A37-F336-43C7-95EB-48827B1D3375.html

**Comment by lilianValeroFp** [comment]
Hi @oleksandriegorov, indeed it is not support by the smc_python lib but you can workaround it by using SMCRequest with ".../system/export_elements" POST operation and "file_password" query parameter. We will handle it in our next release.
