### ISSUE TITLE
Required builtin package distutils removed in Python 3.12

### ISSUE THREAD

**Issue by LaraRamirez** [Forcepoint/fp-NGFW-SMC-python#66]
Hello,

When trying to use smc-python, I get a ModuleNotFoundError: No module named 'distutils'. I can see that this distutils module has been removed in python 3.12 (which is the version I'm using). From the doc there seems to be an alternative called setuptools: https://docs.python.org/3.10/library/distutils.html.

**Comment by LaraRamirez** [comment]
Unable to use smc-python with Python 3.12 as distutils module has been removed:

https://docs.python.org/3.10/library/distutils.html

**Comment by gregory83** [comment]
Hello,

You are right.
We did already found this issue.

In compat.py we did changed import

`
try:
    from packaging.version import Version as LooseVersion
except ImportError:
    try:
        from distutils.version import LooseVersion
    except ImportError as e:
        raise ImportError("Neither 'packaging' nor 'distutils' modules are available. "
                          "Please install 'packaging'.") from e
`

We'll make a new official release as soon as possible with the fix.

/Greg.

**Comment by LaraRamirez** [comment]
Awesome, thank you :)

**Comment by LaraRamirez** [comment]
@gregory83 Just so I can organize my work, do you have any idea on when the release will be? Are we talking days, weeks?

**Comment by gregory83** [comment]
The plan is to release new version the second week of January.
So between 6th and 10th of January.

/Greg.

**Comment by LaraRamirez** [comment]
Ok thank you. Happy holidays and happy new year!
