### ISSUE TITLE
Feature Request: Adding URL block lists via SMC Python

### ISSUE THREAD

**Issue by shibumi** [Forcepoint/fp-NGFW-SMC-python#8]
Hi,
I just realized that you do not support adding URL blocklist via SMC API yet. Is there any plan to support this in the future?

**Comment by shibumi** [comment]
Mh ok, I've found URLApplications: https://smc-python.readthedocs.io/en/latest/pages/reference.html#urllistapplication

but how do I build a blocklist with an URL application?

**Comment by amol-suruse** [comment]
Hello
We have this existing feature that can be used, like in the below example.

    `Layer3Firewall.create(name=ENGINENAME,
                                   mgmt_ip="192.168.10.1",
                                   mgmt_network="192.168.10.0/24")
    policy = FirewallPolicy().create("myPolicy")
    block_list_action = Action()
    block_list_action.action = ["block_list"]
    block_list = list(URLListApplication.objects.all())[0]
    policy.fw_ipv4_access_rules.create(name="block_list_rule", sources="any",
                                       destinations="any", services=[block_list.href],
                                       action=block_list_action)`
